services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:17.2
    env_file:
      - .postgres.env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  db_data:
